// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID           string    `json:"id"`
	PostID       string    `json:"postID"`
	ParentID     *string   `json:"parentID,omitempty"`
	Content      string    `json:"content"`
	Author       *User     `json:"author"`
	CreatedAt    time.Time `json:"createdAt"`
	HaveComments bool      `json:"haveComments"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	AllowComments bool       `json:"allowComments"`
	AuthorID      string     `json:"authorID"`
	HaveComments  bool       `json:"haveComments"`
	CreatedAt     time.Time  `json:"createdAt"`
	Comments      []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}
